#####################################
# Q12: source--> query_vrcc.sparql
# email: 01/12/2016
# BGP: 2
######################################

prefix cdm: <http://publications.europa.eu/ontology/cdm#> 
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
select 
?FIELD_DN 
(group_concat(distinct ?directoryCode; separator="#") as ?FIELD_CC)
where 
{
?act cdm:resource_legal_id_celex ?FIELD_DN. 
?act cdm:resource_legal_id_sector ?sector. 
FILTER (
      ?sector="2"^^<http://www.w3.org/2001/XMLSchema#string>||
      ?sector="3"^^<http://www.w3.org/2001/XMLSchema#string>||
      ?sector="4"^^<http://www.w3.org/2001/XMLSchema#string>||
      ?sector="5"^^<http://www.w3.org/2001/XMLSchema#string>
      ) 
OPTIONAL{
      ?act cdm:resource_legal_is_about_concept_directory-code ?cc.
      BIND(substr(xsd:string(?cc),57) as ?directoryCode).
      }
} group by ?FIELD_DN
order by ?FIELD_DN