#########################################
## Q15 source:--> Preleg_testSet.sparql ##
## CONMAT last modified data
## BGP: 7
#########################################

PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cmr: <http://publications.europa.eu/ontology/cdm/cmr#>

SELECT DISTINCT ?sAcomnat ?dateWork ?lang ?dateExp ?format ?dateMan

WHERE {

{
#pragma values.rewrite.limit 20

?wCOM cdm:work_id_document ?idCOM .
FILTER (?idCOM='comnat:JOIN_2014_0041_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0748_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0733_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0724_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0719_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0716_FIN'^^xsd:string || ?idCOM='comnat:COM_2014_0688_FIN'^^xsd:string || ?idCOM='comnat:COM_2015_0569_FIN'^^xsd:string || ?idCOM='comnat:COM_2015_0627_FIN'^^xsd:string || ?idCOM='comnat:COM_2015_0639_FIN'^^xsd:string ||?idCOM='comnat:COM_2015_0552_FIN'^^xsd:string || ?idCOM='comnat:COM_2016_0106_FIN'^^xsd:string || ?idCOM='comnat:COM_2016_0107_FIN'^^xsd:string || ?idCOM='comnat:COM_2016_0140_FIN'^^xsd:string || ?idCOM='comnat:COM_2016_0141_FIN'^^xsd:string)

}

OPTIONAL {?wCOM cmr:lastModificationDate ?dateWork} .
?wCOM owl:sameAs ?sAcomnat .
FILTER (regex(?sAcomnat, '/comnat/'))
?e cdm:expression_belongs_to_work ?wCOM .
OPTIONAL {?e cmr:lastModificationDate ?dateExp .}
?e owl:sameAs ?sAecomnat .
FILTER (regex(?sAecomnat, 'comnat'))
BIND (strafter(str(?sAecomnat), 'FIN.') as ?lang)
?m cdm:manifestation_manifests_expression ?e .
?m owl:sameAs ?sAman .
FILTER (regex(?sAman, 'comnat'))
BIND (strafter(str(?sAman), '_FIN.') as ?string)
BIND (strafter(?string, '.') as ?format) 
OPTIONAL {?m cmr:lastModificationDate ?dateMan}

} ORDER BY ?sAcomnat ?lang