## Q3: insert a Thread with some attributs
prefix lodep: <https://webgate.acceptance.ec.testa.eu/eparticipation/ontologies/LOD_Eparticipation/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>

INSERT DATA
 { 
 GRAPH <http://lodepart/graph> 

 { 
     <http://localhost:8000/posts/id_user_9/20161122142401/2016/0593/art_1/eng> lodep:num_items_yes 1;
             lodep:num_items_yes  1;
             lodep:num_items_total 1;
             lodep:num_items_yes_na 1;
             a sioc:Thread;
             lodep:num_insertion 0;
       lodep:num_deletion 0;
       lodep:num_substitution 0;
       lodep:num_amendment 0;
      lodep:num_insertion_na 0;
      lodep:num_deletion_na 0;
      lodep:num_substitution_na 0;
      lodep:num_amendment_na 0;                             
  }
  }