##################################################
## Q18: Summaries of EU legislation ##
## Normalized query used in PROD 
## Tree displayed with this SPARQL query #########
## Choose "agriculture" or 
## e.g., ${topicCode} = 010102
###################################################

prefix cdm: <http://publications.europa.eu/ontology/cdm#>
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX ORACLE_SEM_FS_NS:   
<http://oracle.com/semtech#timeout=60,degree=8,ods=6>
# oracle optimization on regex to be changed by <http://xmlns.oracle.com/rdf/like>

# Turn off some special character escaping  
PREFIX ORACLE_SEM_HT_NS: <http://oracle.com/semtech#ESCAPE_STR_FUNC=F,DISABLE_REGEX_UNESC>

select ?summary ?classification (xsd:integer(?obsolete) as ?obsoletes)
where { 
?sum cdm:summary_legislation_eu_is_about_classification_summary ?classification. 
FILTER (<http://xmlns.oracle.com/rdf/like>(?classification, 'http://publications.europa.eu/resource/authority/fd_700/010102')).
?sum ^cdm:expression_belongs_to_work ?expression.
?expression cdm:expression_uses_language ?language.
?sum cdm:summary_legislation_eu_obsolete ?obsolete.
?sum owl:sameAs ?summary.
filter (<http://xmlns.oracle.com/rdf/like>(?summary,'resource/uriserv')).
OPTIONAL{ ?expression cdm:expression_title ?title. }

} order by ?classification
