#Q5: Another Query for setting the inforce flag
# s/{$systemdate}/2007-03-01
# BGP: 5

PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
SELECT * WHERE { 
?s cdm:resource_legal_date_end-of-validity ?date_end.
FILTER not exists {?s cdm:resource_legal_date_end-of-validity ?date_end2.
FILTER(str(?date_end2) >= '2017-03-01' ) }
FILTER(str(?date_end) < '2017-03-01' )
FILTER(str(?date_end) > '1003-03-03' )
OPTIONAL {?s cdm:resource_legal_has_type_act_concept_type_act ?typeact.}
FILTER not exists {?m cdm:manifestation_official-journal_part_durability 'EPH'^^<http://www.w3.org/2001/XMLSchema#string>.?m cdm:manifestation_manifests_expression ?e.?e cdm:expression_belongs_to_work ?s.}
OPTIONAL{?s cdm:resource_legal_id_celex ?celex.}
MINUS { ?s cdm:resource_legal_in-force ?inforce. FILTER(?inforce="false" ^^<http://www.w3.org/2001/XMLSchema#boolean>) }
 }