#########################################
#Q8: Query for setting the pending flag
#BGP: 4
#########################################
## update June 2022
## Changed FILTER(?pending="true"^^xsd:boolean) with FILTER(?pending="false"^^xsd:boolean)

#DEFINE input:inference "cdm_rule_set"
prefix cdm: <http://publications.europa.eu/ontology/cdm#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select distinct ?dossier where
{
?dossier_cellar owl:sameAs ?dossier.
FILTER(regex(str(?dossier),'procedure'))
?dossier_cellar a cdm:dossier.
?dossier_cellar a cdm:procedure_code_interinstitutional.
?dossier_cellar cdm:dossier_initiated_by_act_preparatory ?work.
?event cdm:event_legal_contains_work ?work.
?event (cdm:event_date|cdm:event_legal_date) ?date.
FILTER(?date >= '2015-06-29' ^^<http://www.w3.org/2001/XMLSchema#date>)
MINUS
{
?dossier_cellar cdm:dossier_withdrawn-proposal ?withdrawn.
FILTER(?withdrawn="true"^^xsd:boolean)
}
MINUS
{
?dossier_cellar cdm:dossier_adopted-proposal ?adopted.
FILTER(?adopted="true"^^xsd:boolean)
}
MINUS
{
?dossier_cellar cdm:dossier_pending-proposal ?pending.
FILTER(?pending="false"^^xsd:boolean)
}
}