## Q2: increments num_items of each container in the SPARQL results
## first of all, we delete old statistics (?total, ?totalna, ?note, ?notena) and replace by new statistics (?newTotal, ?newTotalna, ?newNote, ?newNotena)

#Error with qparse jena tool. 
#Query OK according to sparql.org update validator
# sample update query
#Note: In case of Jena parsing error, use DELETE { GRAPH <g1> { a b c } } INSERT { GRAPH <g1> { x y z } } USING <g1> WHERE { ... }


prefix lodep: <https://webgate.acceptance.ec.testa.eu/eparticipation/ontologies/LOD_Eparticipation/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

WITH <http://lodepart/graph> DELETE  {

                ?val lodep:num_items_total ?total. 
                ?val lodep:num_items_yes  ?note. 
                ?val lodep:num_items_total_na ?totalna. 
                ?val lodep:num_items_yes_na ?notena. 
                } 
                 # and update statistics about comments by increasing by 1
                INSERT {
                ?val lodep:num_items_total ?newtotal.
                ?val lodep:num_items_yes ?newnote.
                ?val lodep:num_items_total_na ?newtotalna.
                ?val lodep:num_items_yes_na ?newnotena. 
               }
                
               WHERE {
                        OPTIONAL{?val lodep:num_items_total ?total. BIND ((xsd:integer(?total) + 1) AS ?newtotal)}
                        OPTIONAL{?val lodep:num_items_total_na ?totalna. BIND ((xsd:integer(?totalna) + 1) AS ?newtotalna)}
	                    OPTIONAL{?val lodep:num_items_yes_na ?notena. BIND ((xsd:integer(?notena) + 1) AS ?newnotena)}
                        OPTIONAL{?val lodep:num_items_yes ?note. BIND ((xsd:integer(?note) + 1) AS ?newnote)}
                     }

