## Q4: Query to put in the dataset the hierarchy of containers (has_parent or realization_of)
## adding inverse of relations 
PREFIX  sioc: <http://rdfs.org/sioc/ns#>
PREFIX  lodep: <https://webgate.acceptance.ec.testa.eu/eparticipation/ontologies/LOD_Eparticipation/>

WITH <http://lodepart/graph>
INSERT  
 {
     ?x sioc:has_parent <http://dbpedia.org/resource/Barack_Obama,_Sr.> .
     ?y sioc:parent_of <http://dbpedia.org/resource/Barack_Obama> .
     ?x lodep:realization_of ?y .
     ?y lodep:realization_by ?x . 

}
WHERE
{
?x sioc:has_parent ?y .
     ?y sioc:parent_of ?x .
     ?x lodep:realization_of ?y .
     ?y lodep:realization_by ?x . 	
}

