## Q5: Query to insert a post 
PREFIX  lodep: <https://webgate.acceptance.ec.testa.eu/eparticipation/ontologies/LOD_Eparticipation/>
PREFIX  sioc: <http://rdfs.org/sioc/ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT DATA
{GRAPH <http://lodepart/graph> 
		{
		<http://localhost:8000/posts/id_user_9/20161122142401/2016/0593/art_1/eng> a sioc:Post;
		sioc:content "This is my comment.."@eng;
		sioc:has_creator <http://localhost:8000/user/id_user_9>;
		sioc:note "yes"^^rdfs:Literal;
		sioc:created_at "2016-12-20"; 
		sioc:has_container <http://localhost:8000/eli/PROP_DIR/2016/0593/art_1/eng>;
		lodep:num_like 0;
		lodep:num_dislike 0.
		} 
	}