## Q5L - Query from Open Data Portal log
## filter, regex and limit

PREFIX lemon: <http://www.lemon-model.net/lemon#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX jrc-model: <http://data.europa.eu/euodp/resource/jrc-names#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT
  ?dbpedia (CONCAT("<http://dbpedia.org/ext/jrc-label", str(?id), ">") AS ?jrcid) ?Rep 
WHERE
  {
    ?variant rdf:type lemon:LexicalEntry .
    ?variant lemon:sense ?sense .
    ?sense lemon:reference ?ref .
    ?ref owl:sameAs ?dbpedia .
    FILTER ( regex(str(?dbpedia), "http://dbpedia.org/resource/.*" )).
    ?variant lemon:canonicalForm ?form .
    ?form lemon:writtenRep ?Rep .
    ?ref jrc-model:hasId ?id .
  }  LIMIT 200