##Q13: ##########################################
### Not normalized query (not used in PROD): ####
## NIM Tab default
## BGP: 12
## sample <http://publications.europa.eu/resource/celex/32012L0027>
#################################################

prefix cdm: <http://publications.europa.eu/ontology/cdm#> 
prefix annotation: <http://publications.europa.eu/ontology/annotation#>
prefix owl: <http://www.w3.org/2002/07/owl#>

select distinct ?eli ?country ?nim_id ?transposition_deadline ?transposition_status ?oj_name ?oj_number ?oj_date ?oj_page ?expr_language ?title ?entry_into_force ?reference_commission ?date_notification 
{ select distinct ?eli ?country ?nim_id ?transposition_deadline ?transposition_status ?oj_name ?oj_number ?oj_date ?oj_page ?expr_language ?title ?entry_into_force ?reference_commission ?date_notification 
  where { <http://publications.europa.eu/resource/celex/32012L0027> ^owl:sameAs/owl:sameAs/cdm:work_date_document ?wdd. 
  OPTIONAL { <http://publications.europa.eu/resource/celex/32012L0027> cdm:resource_legal_eli ?eli.} 
  OPTIONAL { ?mne cdm:measure_national_implementing_implements_directive <http://publications.europa.eu/resource/celex/32012L0027>; cdm:measure_national_implementing_implemented_by_country ?country. 
  OPTIONAL { ?s annotation:transposition_deadline_transmitted ?transposition_deadline. ?s owl:annotatedSource ?mne. ?s owl:annotatedProperty cdm:measure_national_implementing_implements_directive. 
    ?s owl:annotatedTarget/^owl:sameAs/owl:sameAs <http://publications.europa.eu/resource/celex/32012L0027>. } 
  OPTIONAL {?mne cdm:measure_national_implementing_declaration_transposition_member-state ?transposition_status.} 
  OPTIONAL { ?mne ^owl:sameAs/owl:sameAs ?nim_id. FILTER (regex(?nim_id, '/resource/nim/')) ?mne ^owl:sameAs/owl:sameAs ?celex_id. FILTER (regex(?celex_id, '/resource/celex/')) } FILTER(!regex(?celex_id,'%2528.*%2529')) 
  OPTIONAL {?mne cdm:measure_national_implementing_name_official_journal ?oj_name.} 
  OPTIONAL {?mne cdm:measure_national_implementing_number_official_journal ?oj_number.} 
  OPTIONAL {?mne cdm:measure_national_implementing_date_official_journal ?oj_date.} 
  OPTIONAL {?mne cdm:measure_national_implementing_page_official_journal ?oj_page.} 
  OPTIONAL {?mne cdm:resource_legal_date_entry-into-force ?entry_into_force.} 
  OPTIONAL {?mne cdm:measure_national_implementing_reference_commission ?reference_commission.}
   OPTIONAL {?mne cdm:measure_national_implementing_date_notification ?date_notification.} ?exp cdm:expression_belongs_to_work ?mne; cdm:expression_uses_language ?expr_language; cdm:expression_title ?title. }}} ORDER BY ?country

