#################################################
## Q16: Query rectified applicable only in Test##
## test with doc Celex 62013TO0583
## exple of ${language}= ENG, FRA, ITA, DEUS
## BGP: 4 
###################################################


prefix cdm: <http://publications.europa.eu/ontology/cdm#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?date ?lang ?type ?celex ?rectificationOrderCelex 
where 
{ ?uri cdm:work_datetime_transmission ?date. 
  OPTIONAL{ 
  ?rectificationOrder cdm:resource_legal_corrects_resource_legal ?uri; cdm:resource_legal_id_celex ?rectificationOrderCelex. } 

  ?uri ^cdm:expression_belongs_to_work ?exp. 
  ?exp cdm:expression_uses_language ?lang;
^cdm:manifestation_manifests_expression ?manif. 
?manif cdm:manifestation_type ?type. 
?uri owl:sameAs ?celex. 
FILTER contains(str(?celex), "62013TO0583"). 
  
  VALUES ?uri {<http://publications.europa.eu/resource/cellar/6df75a83-c084-11e3-86f9-01aa75ed71a1> <http://publications.europa.eu/resource/cellar/3415a9e7-1d14-4017-95c1-aecec43462d5.0022>
  	   <http://publications.europa.eu/resource/cellar/771a3fe7-b701-438b-b8af-a94ed340fd63>}
} ORDER BY DESC(?date) ?uri ?lang ?type
