# Q1:
# LODep: select from the dataBase the list of triples, whose have to be incremented (number of comments, ..)
#BGP: 6 
# fixed version for bench


PREFIX  lodep: <https://webgate.acceptance.ec.testa.eu/eparticipation/ontologies/LOD_Eparticipation/>
PREFIX ORACLE_SEM_FS_NS:   
<http://oracle.com/semtech#timeout=10,degree=8,ods=6>

SELECT DISTINCT  ?container ?total ?totalna ?note ?notena
WHERE
  {   { OPTIONAL
          { ?container lodep:num_items_total ?total }
        OPTIONAL
          { ?container lodep:num_items_yes ?note }
        OPTIONAL
          { ?container lodep:num_items_yes_na ?notena }
        OPTIONAL
          { ?container lodep:num_items_total_na ?totalna }
        FILTER ( ?container = <http://localhost:8000/eli/PROP_DIR/2016/0593/art_1/eng> )
      }
    UNION
      { OPTIONAL
          { ?container lodep:num_items_total ?total }
        OPTIONAL
          { ?container lodep:num_items_yes ?note }
      }
  }
