##Q14: ##########################################
### Normalized query ( used in PROD): ###########
## List contains documents with titles ##########
## test with doc Celex 52011DC0666
## exple of ${language}= ENG, FRA, ITA, DEUS
## BGP: 3
#################################################

PREFIX ORACLE_SEM_FS_NS:   
<http://oracle.com/semtech#timeout=60,degree=8,ods=6>

# Turn off some special character escaping  
PREFIX ORACLE_SEM_HT_NS: <http://oracle.com/semtech#ESCAPE_STR_FUNC=F,DISABLE_REGEX_UNESC>

# Oracle optimization for regex to be replaced by <http://xmlns.oracle.com/rdf/like>

prefix cdm: <http://publications.europa.eu/ontology/cdm#>
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

select distinct ?summary ?title where { ?sum owl:sameAs ?summary. filter (<http://xmlns.oracle.com/rdf/like>(?summary, '/resource/uriserv/')). 
OPTIONAL {?sum ^cdm:expression_belongs_to_work ?e. ?e cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/FRA>; cdm:expression_title ?title.} 
{ select DISTINCT ?sum where { ?s cdm:resource_legal_id_celex "52011DC0666"^^xsd:string; ^cdm:summary_summarizes_work ?sum. }} }
