# Q2. %%%%%%%%%%%%%%%%%%%%%%%%%%%%
## Goal: Compute non-inferred symmetric concise bounded branch description.
## language code of desired branch. A branch notice only contains the expression specified by the language code. 
## Virtuoso allows to customize the output of a SPARQL DESCRIBE with help of a sql:describe-mode pragma.
## Requirements: We intend to use the query for on-the-fly notice generation. 

## Oracle optimization replacing single-value VALUES clauses with an equivalent BIND clause
#DEFINE sql:describe-mode "SCBD"
PREFIX ORACLE_SEM_FS_NS:   
<http://oracle.com/semtech#timeout=60,degree=8,ods=6>

# Turn off some special character escaping  
PREFIX ORACLE_SEM_HT_NS: <http://oracle.com/semtech#ESCAPE_STR_FUNC=F,DISABLE_REGEX_UNESC>

prefix cdm: <http://publications.europa.eu/ontology/cdm#>
prefix owl: <http://www.w3.org/2002/07/owl#> 

describe ?w ?e ?m where
{
	# substitute cellar id here 
	#values ?w {<http://publications.europa.eu/resource/cellar/6df75a83-c084-11e3-86f9-01aa75ed71a1>}
	BIND(<http://publications.europa.eu/resource/cellar/6df75a83-c084-11e3-86f9-01aa75ed71a1> AS  ?w)
	?e cdm:expression_belongs_to_work ?w;
	# substitute language code here
	cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/POR>.
	optional{?m cdm:manifestation_manifests_expression ?e.}
}
