###############################
##Q6: Dynamic Query ###########
###############################

PREFIX ORACLE_SEM_FS_NS:   
<http://oracle.com/semtech#timeout=60,degree=8,ods=6>

## oracle optimization on group_concat 
## For group_concat, remove the distinct and wrap the first input with STR().

# Turn off some special character escaping  
PREFIX ORACLE_SEM_HT_NS: <http://oracle.com/semtech#ESCAPE_STR_FUNC=F,DISABLE_REGEX_UNESC>


PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX eurovoc: <http://eurovoc.europa.eu/schema#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
SELECT ?work 
       ((?abstract) as ?abstracts)  
       (group_concat(STR(?title_);separator=", ") as ?title) 
       ?date
     
       (group_concat(STR(?workId);separator=", ") as ?workIds) 
      (group_concat(STR(?workType);separator=", ") as ?workTypes)
      (group_concat(STR(?subject);separator=", ") as ?subjects) 
      (group_concat(STR(?author);separator=", ") as ?authors)
      (group_concat(STR(?work);separator=", ") as ?cellarURIs)
      (group_concat(STR(?mtype);separator=", ") as ?mtypes)WHERE {
   ?work cdm:work_is_about_concept_eurovoc/dc:identifier ?subject;
   cdm:work_id_document ?workId;
   rdf:type ?workType;
   cdm:work_created_by_agent/dc:identifier ?author.
   ?expr cdm:expression_belongs_to_work ?work.
   optional {?expr cdm:expression_title ?title_;
                   cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/ENG>.}
   optional {?expr cdm:expression_abstract ?abstract}.
   optional {?m cdm:manifestation_manifests_expression ?expr; cdm:manifestation_type ?mtype}
{
   SELECT DISTINCT ?work ?date WHERE {
?work cdm:work_is_about_concept_eurovoc/dc:identifier "3493";
      cdm:work_date_document ?date.
?expr2 cdm:expression_belongs_to_work ?work.
 ?expr2 cdm:expression_title ?title2;
      cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/ENG>. 
?work cdm:work_created_by_agent/dc:identifier "EC".
}
ORDER BY DESC(?date)
OFFSET 0
LIMIT 10 }
}
GROUP BY ?work ?date ?abstract
